### ISSUE TITLE
Relative call ruined my CTF

### ISSUE THREAD

**Issue by geohot** [BinaryAnalysisPlatform/qira#76]
![image](https://cloud.githubusercontent.com/assets/72895/6422916/20d1512a-be93-11e4-96f7-ec5aa415874f.png)

Why is that callq PC relative? Capstone used to work, why did BAP break it?

But seriously, things like this are why the current QIRA is unusable, and I'm still stuck on 1.0

**Comment by nedwill** [comment]
Yeah, Capstone would always display jumps as absolute whereas now BAP gives us the call as PC relative. We're aware of the issue and will fix it. We might have to do some string hacks because that's just the disassembly string. We do handle this in static itself, it's just not correct on the frontend.

**Comment by crowell** [comment]
you can thank @acama for this zweet bug ;-)

**Comment by ivg** [comment]
BAP from today has a native x86 family lifter. My next release will be about bap+qira, I'm going to add bap as static backend, since now it is quite good at cfg reconstruction and function finding (not only starts – both ends). Also, BAP now has an integration with IDA, so it can provide FLIRT info for QIRA.

**Comment by acama** [comment]
your welcome :)

**Comment by nedwill** [comment]
Tim fixed this. I'll be doing war games over spring break with QIRA so hopefully I can pick up on more usability issues. Sorry for the sad CTF experience!
